// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// st_dbscan_cpp
IntegerVector st_dbscan_cpp(NumericVector x, NumericVector y, NumericVector t, double eps_spatial, double eps_temporal, int minPts);
RcppExport SEXP _stdbscan_st_dbscan_cpp(SEXP xSEXP, SEXP ySEXP, SEXP tSEXP, SEXP eps_spatialSEXP, SEXP eps_temporalSEXP, SEXP minPtsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type eps_spatial(eps_spatialSEXP);
    Rcpp::traits::input_parameter< double >::type eps_temporal(eps_temporalSEXP);
    Rcpp::traits::input_parameter< int >::type minPts(minPtsSEXP);
    rcpp_result_gen = Rcpp::wrap(st_dbscan_cpp(x, y, t, eps_spatial, eps_temporal, minPts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stdbscan_st_dbscan_cpp", (DL_FUNC) &_stdbscan_st_dbscan_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_stdbscan(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
