// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// temporal_filter_cpp
List temporal_filter_cpp(List id, List dist, NumericVector t, double eps_temporal);
RcppExport SEXP _stdbscan_temporal_filter_cpp(SEXP idSEXP, SEXP distSEXP, SEXP tSEXP, SEXP eps_temporalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type id(idSEXP);
    Rcpp::traits::input_parameter< List >::type dist(distSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type eps_temporal(eps_temporalSEXP);
    rcpp_result_gen = Rcpp::wrap(temporal_filter_cpp(id, dist, t, eps_temporal));
    return rcpp_result_gen;
END_RCPP
}
// temporal_filter_pred_cpp
List temporal_filter_pred_cpp(List id, NumericVector n_t, NumericVector t, double eps_temporal);
RcppExport SEXP _stdbscan_temporal_filter_pred_cpp(SEXP idSEXP, SEXP n_tSEXP, SEXP tSEXP, SEXP eps_temporalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type n_t(n_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type eps_temporal(eps_temporalSEXP);
    rcpp_result_gen = Rcpp::wrap(temporal_filter_pred_cpp(id, n_t, t, eps_temporal));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stdbscan_temporal_filter_cpp", (DL_FUNC) &_stdbscan_temporal_filter_cpp, 4},
    {"_stdbscan_temporal_filter_pred_cpp", (DL_FUNC) &_stdbscan_temporal_filter_pred_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_stdbscan(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
