# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

st_dbscan_cpp <- function(x, y, t, eps_spatial, eps_temporal, minPts) {
    .Call(`_stdbscan_st_dbscan_cpp`, x, y, t, eps_spatial, eps_temporal, minPts)
}

