# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

temporal_filter_cpp <- function(id, dist, t, eps_temporal) {
    .Call(`_stdbscan_temporal_filter_cpp`, id, dist, t, eps_temporal)
}

temporal_filter_pred_cpp <- function(id, n_t, t, eps_temporal) {
    .Call(`_stdbscan_temporal_filter_pred_cpp`, id, n_t, t, eps_temporal)
}

